export type SingleOrMultiple<T> = T | T[];
export { VOXEL_TAGS } from "@/Voxel";

export { Datapack } from "@/core/Datapack";
export { Tags, isTag } from "@/core/Tag";
export { Identifier, isIdentifier } from "@/core/Identifier";
export { EnchantmentSorter } from "@/core/schema/enchant/Sorter";
export { LootTableFlattener } from "@/core/calculation/LootTableFlattener";
export { EnchantmentSimulator } from "@/core/calculation/EnchantmentSimulation";
export { Logger } from "@/core/engine/migrations/logger";
export { TagsComparator } from "@/core/TagComparator";
export { DatapackError } from "@/core/DatapackError";
export { TagCompiler } from "@/core/TagCompiler";
export { LootTableAppearanceProbability } from "@/core/calculation/LootTableAppearanceProbability";
export { CoreActions } from "@/core/engine/actions/domains/CoreAction";
export { RecipeActions } from "@/core/engine/actions/domains/RecipeAction";
export { LootTableActions } from "@/core/engine/actions/domains/LootTableAction";
export { StructureActions } from "@/core/engine/actions/domains/StructureAction";
export { StructureSetActions } from "@/core/engine/actions/domains/StructureSetAction";
export { EnchantmentActions } from "@/core/engine/actions/domains/EnchantmentAction";

export { PACK_VERSION, getMinecraftVersion } from "@/core/Version";
export { analyserCollection, isVoxel } from "@/core/engine/Analyser";
export { getLabeledIdentifier, isVoxelElement } from "@/core/Element";
export { getItemFromMultipleOrOne, getAllItems, separateItemsAndTags } from "@/core/ItemList";
export { updateData } from "@/core/engine/actions/index";
export { calculateItemCountRange } from "@/core/calculation/LootCountProbability";
export { toRoman } from "@/Roman";
export { flattenSlots } from "@/core/engine/managers/SlotManager";
export { compileDatapack } from "@/core/engine/Compiler";
export { parseDatapack } from "@/core/engine/Parser";

export type { EnchantmentSortCriteria } from "@/core/schema/enchant/Sorter";
export type { FlattenedLootItem } from "@/core/calculation/LootTableFlattener";
export type { EnchantmentOption, EnchantmentStats, SlotLevelRange } from "@/core/calculation/EnchantmentSimulation";
export type { IdentifierObject } from "@/core/Identifier";
export type { Compiler } from "@/core/engine/Compiler";
export type { Parser, ParseDatapackResult } from "@/core/engine/Parser";
export type { DataDrivenElement, DataDrivenRegistryElement, LabeledElement, VoxelElement } from "@/core/Element";
export type { Analysers, Analyser, GetAnalyserVoxel } from "@/core/engine/Analyser";
export type { Action, ActionValue, ActionLike } from "@/core/engine/actions/types";
export type { SlotRegistryType } from "@/core/engine/managers/SlotManager";
export type { TextComponentType } from "@/core/schema/TextComponentType";
export type { TagType, OptionalTag, TagRegistry } from "@/core/Tag";
export type { StructureProps } from "@/core/schema/structure/types";
export type { StructureSetProps } from "@/core/schema/structure_set/types";
export type { RecipeProps } from "@/core/schema/recipe/types";
export type { EnchantmentProps } from "@/core/schema/enchant/types";
export type { Enchantment } from "@/core/schema/enchant/types";
export type { LootItem, LootGroup, MinecraftLootEntry, LootTableProps, MinecraftLootTable } from "@/core/schema/loot/types";
