export type SingleOrMultiple<T> = T | T[];
export { VOXEL_TAGS } from "@/Voxel";

export { Datapack } from "@/core/Datapack";
export { Tags } from "@/core/Tag";
export { Identifier } from "@/core/Identifier";
export { FileStatusComparator, FILE_STATUS } from "@/core/FileStatusComparator";
export { EnchantmentSorter } from "@/core/schema/enchant/Sorter";
export { LootTableFlattener } from "@/core/calculation/LootTableFlattener";
export { EnchantmentSimulator } from "@/core/calculation/EnchantmentSimulation";
export { Logger } from "@/core/engine/migrations/logger";
export { TagsProcessor as TagsComparator } from "@/core/TagsProcessor";
export { TagsProcessor } from "@/core/TagsProcessor";
export { DatapackError } from "@/core/DatapackError";
export { LootTableAppearanceProbability } from "@/core/calculation/LootTableAppearanceProbability";
export { SlotManager } from "@/core/SlotManager";

export { Action } from "@/core/engine/actions/index";
export { CoreAction } from "@/core/engine/actions/domains/CoreAction";
export { RecipeAction } from "@/core/engine/actions/domains/RecipeAction";
export { LootTableAction } from "@/core/engine/actions/domains/LootTableAction";
export { StructureAction } from "@/core/engine/actions/domains/StructureAction";
export { StructureSetAction } from "@/core/engine/actions/domains/StructureSetAction";
export { EnchantmentAction } from "@/core/engine/actions/domains/EnchantmentAction";

export { PACK_VERSION, getMinecraftVersion } from "@/core/Version";
export { analyserCollection, isVoxel } from "@/core/engine/Analyser";
export { isVoxelElement } from "@/core/Element";
export { getItemFromMultipleOrOne, getAllItems, separateItemsAndTags } from "@/core/ItemList";
export { updateData } from "@/core/engine/actions/index";
export { calculateItemCountRange } from "@/core/calculation/LootCountProbability";
export { toRoman } from "@/Roman";
export { compileDatapack } from "@/core/engine/Compiler";
export { parseDatapack } from "@/core/engine/Parser";

export type { IdentifierObject } from "@/core/Identifier";
export type { FileStatus } from "@/core/FileStatusComparator";
export type { EnchantmentSortCriteria } from "@/core/schema/enchant/Sorter";
export type { FlattenedLootItem } from "@/core/calculation/LootTableFlattener";
export type { EnchantmentOption, EnchantmentStats, SlotLevelRange } from "@/core/calculation/EnchantmentSimulation";
export type { Compiler } from "@/core/engine/Compiler";
export type { Parser, ParseDatapackResult } from "@/core/engine/Parser";
export type { DataDrivenElement, DataDrivenRegistryElement, VoxelElement } from "@/core/Element";
export type { Analysers, Analyser, GetAnalyserVoxel } from "@/core/engine/Analyser";
export type { ActionValue } from "@/core/engine/actions/index";
export type { SlotRegistryType } from "@/core/SlotManager";
export type { TextComponentType } from "@/core/schema/TextComponentType";
export type { TagType, OptionalTag } from "@/core/Tag";
export type { StructureProps } from "@/core/schema/structure/types";
export type { StructureSetProps } from "@/core/schema/structure_set/types";
export type { RecipeProps } from "@/core/schema/recipe/types";
export type { EnchantmentProps, Enchantment } from "@/core/schema/enchant/types";
export type { LootItem, LootGroup, MinecraftLootEntry, LootTableProps, MinecraftLootTable } from "@/core/schema/loot/types";
