import type { ModMetadata, ModPlatformType } from "@/types";
import { DEFAULT_MOD_METADATA, ModPlatforms } from "@/types";

const LOADER_CONFIG = {
	[ModPlatforms.FORGE]: { loader: "lowcodefml", version: "[40,)" },
	[ModPlatforms.NEOFORGE]: { loader: "javafml", version: "[1,)" }
} as const;

const escapeToml = (str: string) => str.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n");
const buildModEntry = (mod: ModMetadata): string => {
	const fields = new Map([
		["modId", mod.id],
		["version", mod.version],
		["displayName", mod.name],
		["description", escapeToml(mod.description)],
		["credits", "Generated by DatapackConverter"]
	]);

	if (mod.icon) fields.set("logoFile", mod.icon);
	if (mod.authors.length) fields.set("authors", mod.authors.join(", "));

	if (mod.homepage && mod.homepage !== DEFAULT_MOD_METADATA.homepage) {
		fields.set("updateJSONURL", `${mod.homepage}/updates.json`);
		fields.set("displayURL", mod.homepage);
	}

	return `\t{ ${[...fields].map(([k, v]) => `${k} = "${v}"`).join(", ")} }`;
};

/**
 * Generates TOML content for Forge/NeoForge mods
 * @param commonData - Common mod metadata
 * @param platforms - Target platforms (affects loader generation)
 * @returns Formatted TOML content for mods.toml
 */
export function generateForgeMods(metadata: ModMetadata, platforms: ModPlatformType[]) {
	const config = platforms.includes(ModPlatforms.FORGE) ? LOADER_CONFIG[ModPlatforms.FORGE] : LOADER_CONFIG[ModPlatforms.NEOFORGE];
	const fields = new Map<string, string | boolean>([
		["modLoader", config.loader],
		["loaderVersion", config.version],
		["license", "LicenseRef-Datapack"],
		["showAsResourcePack", false]
	]);

	if (metadata.issues && metadata.issues !== DEFAULT_MOD_METADATA.issues) {
		fields.set("issueTrackerURL", metadata.issues);
	}

	const lines = [...fields].map(([key, value]) => (typeof value === "boolean" ? `${key} = ${value}` : `${key} = '${value}'`));
	return [...lines, "mods = [", buildModEntry(metadata), "]"].join("\n");
}
