import { describe, it, expect } from "vitest";
import { generateForgeMods } from "@/forge-neoforge";
import { ModPlatforms } from "@/types";
import { createTestMetadata } from "./mock";

describe("generateForgeMods", () => {
    it("should generate valid mods.toml structure for Forge", () => {
        const testMetadata = createTestMetadata({
            authors: ["TestAuthor", "AnotherAuthor"],
            icon: "icon.png",
            homepage: "https://example.com",
            issues: "https://example.com/issues",
            sources: "https://example.com/source",
        });

        const result = generateForgeMods(testMetadata, [ModPlatforms.FORGE]);
        expect(result).toContain("modLoader = 'lowcodefml'");
        expect(result).toContain("loaderVersion = '[40,)'");
        expect(result).toContain("license = 'LicenseRef-Datapack'");
        expect(result).toContain("showAsResourcePack = false");
        expect(result).toContain('modId = "test_mod"');
        expect(result).toContain('version = "1.0.0"');
        expect(result).toContain('displayName = "Test Mod"');
        expect(result).toContain('description = "A test mod for unit testing"');
        expect(result).toContain('logoFile = "icon.png"');
        expect(result).toContain('authors = "TestAuthor, AnotherAuthor"');
        expect(result).toContain('credits = "Generated by DatapackConverter"');
        expect(result).toContain('displayURL = "https://example.com"');
        expect(result).toContain('updateJSONURL = "https://example.com/updates.json"');
        expect(result).toContain("issueTrackerURL = 'https://example.com/issues'");
    });

    it("should generate valid mods.toml structure for NeoForge", () => {
        const testMetadata = createTestMetadata();
        const result = generateForgeMods(testMetadata, [ModPlatforms.NEOFORGE]);
        expect(result).toContain("modLoader = 'javafml'");
        expect(result).toContain("loaderVersion = '[1,)'");
        expect(result).toContain("license = 'LicenseRef-Datapack'");
        expect(result).toContain("showAsResourcePack = false");
        expect(result).toContain('modId = "test_mod"');
        expect(result).toContain('version = "1.0.0"');
        expect(result).toContain('displayName = "Test Mod"');
        expect(result).toContain('description = "A test mod for unit testing"');
    });

    it("should omit optional fields when not provided", () => {
        const minimalMetadata = createTestMetadata({ id: "minimal_mod", name: "Minimal Mod", description: "Minimal description" });
        const result = generateForgeMods(minimalMetadata, [ModPlatforms.FORGE]);
        expect(result).not.toContain("logoFile");
        expect(result).not.toContain("authors =");
        expect(result).not.toContain("displayURL");
        expect(result).not.toContain("updateJSONURL");
        expect(result).not.toContain("issueTrackerURL");
        expect(result).toContain('credits = "Generated by DatapackConverter"');
    });

    it("should properly escape quotes in description", () => {
        const metadataWithQuotes = createTestMetadata({ description: 'A mod with "quoted" text' });
        const result = generateForgeMods(metadataWithQuotes, [ModPlatforms.FORGE]);
        expect(result).toContain('description = "A mod with \\"quoted\\" text"');
    });
});
